diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'

urlpatterns = [
    path('create_post/', views.PostCreate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('delete_post/<int:pk>/', views.delete_post, name='post_delete'),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('', views.PostList.as_view()),
    path('guest_book', views.guest_book, name='guest_book'),
    path('guest_write', views.guest_write, name='guest_write'),
    path('guest_delete/<int:pk>/', views.guest_delete, name='guest_delete'),
    path('avatar', views.avatar),
    path('avatar_profile',views.avatar_profile, name='avatar_profile')
]

my_diary/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('diary/', include('diary.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('single_pages.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

single_pages/urls.py
from django.urls import path
from . import views

app_name = 'single_pages'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('list', views.list, name='list'),
    path('write', views.write, name='write'),
    path('delete/<int:id>/',views.delete,name='delete'),
    path('information', views.information, name='information'),
    path('login', views.login,name='login'),
]

diary/models.py
from django.db import models
import os

class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()

    head_image = models.ImageField(upload_to='diary/images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(upload_to='diary/files/%Y/%m/%d/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'[{self.pk}]{self.title}'

    def get_absolute_url(self):
        return f'/diary/{self.pk}/'

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)
    
    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]



class Guest(models.Model):
    author = models.CharField(null=True,max_length=20)
    content=models.TextField()
    created_at =models.DateTimeField(auto_now_add=True)
    sticker=models.CharField(null=True, max_length=100)

    def __str__(self):
        return f'{self.author},{self.content}'

    def get_absolute_url(self):
        return f'/diary/guest_book/#guest-{self.pk}'

single_pages/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'[{self.pk}]{self.title}'

    def get_absolute_url(self):
        return f'/single_pages/{self.pk}/'

class Comment(models.Model):
    question = models.CharField(null=True, max_length=50)
    content=models.TextField()
    created_at =models.DateTimeField(auto_now_add=True)
    modified_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.question},{self.content}'

    def get_absolute_url(self):
        return f'/list/#comment-{self.pk}'


class Information(models.Model):
    name = models.CharField(null=True, max_length=10)
    email = models.EmailField(null=True, max_length=30)
    instagram = models.URLField(null=True)
    mbti = models.CharField(null=True, max_length=7)

    def __str__(self):
        return f'[Update{self.pk}] Information'

class Profile(models.Model):
    profile = models.ImageField(null=True, blank=True)

    def __str__(self):
        return f'{self.pk} Profile'

diary/views.py
import base64

from single_pages.models import Profile
import os
from django.conf import settings
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from .models import Post, Guest
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from PIL import Image

class PostList(LoginRequiredMixin, ListView):
    model = Post
    ordering = 'pk'
    paginate_by = 8


class PostDetail(DetailView):
    model = Post


class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'head_image', 'file_upload']

    def test_func(self):
        return self.request.user.is_superuser

    def form_valid(self, form):
        current_user = self.request.user
        if not (current_user.is_authenticated and current_user.is_superuser):
            return redirect('/diary/')
        else:
            response = super(PostCreate, self).form_valid(form)
            return response


class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'head_image', 'file_upload']

    template_name = 'diary/post_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

def delete_post(request, pk):
    post = Post.objects.filter(pk=pk)
    if post:
        post.delete()
        return redirect('/diary/')


@login_required
def guest_book(request):
    guest_list = Guest.objects.all().order_by('-created_at')
    paginator = Paginator(guest_list, 7)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'diary/guest_book.html', {'page_obj': page_obj})


def guest_write(request):
    guest = Guest()
    guest.author = request.POST['author']
    guest.content = request.POST['content']
    guest.sticker = request.POST['sticker']
    guest.save()

    return HttpResponseRedirect('guest_book')


def guest_delete(request, pk):
    guest = Guest.objects.filter(pk=pk)
    if guest:
        guest.delete()
    return redirect('/diary/guest_book')


@login_required
def avatar(request):
    return render(request, 'diary/avatar.html')


@csrf_exempt
def avatar_profile(request):
    data = request.POST.__getitem__('data')
    data = data[22:]

    filename = 'profile.png'
    imgdata = base64.b64decode(data)
    img_root = settings.MEDIA_ROOT+ '/'+ filename
    with open(img_root,'wb') as f:
        f.write(imgdata)

    profile = Profile()
    profile.profile = Image.open(img_root)
    profile.save()

    return HttpResponseRedirect('avatar')

single_pages/views.py
from datetime import datetime
from django.shortcuts import redirect, render
from .models import Comment, Information, Profile
from diary.models import Post
from django.http import HttpResponseRedirect
import json

def landing(request):
    if request.user.is_authenticated:
        profile = Information.objects.last()
        postall=Post.objects.all().order_by('-created_at')
        img = Profile.objects.last()
        information = {'profile':profile, 'postall':postall, 'img':img}

        return render(request, 'single_pages/landing.html', information)
    else:
        return HttpResponseRedirect('login')

def login(request):
    return render(
        request,
        'single_pages/cover.html'
    )

def list(request):
    commentlist=Comment.objects.all().order_by('-created_at')
    data={'commentlist':commentlist}
    return render(request, 'single_pages/list.html',data)

def write(request):
    comment = Comment()
    comment.question=request.POST['question']
    comment.content=request.POST['content']
    comment.save()
    return HttpResponseRedirect('list')

def delete(request,id):
    comment = Comment.objects.filter(pk=id)
    if comment:
        comment.delete()
    return redirect('/list')

def information(request):
    information = Information()
    information.name = request.POST['name']
    information.email = request.POST['email']
    information.instagram = request.POST['instagram']
    information.mbti = request.POST['mbti']
    information.save()

    return redirect('/')

diary/templates/diary/avatar.html
<!DOCTYPE html>
<html lang="ko">

{% extends 'single_pages/base.html' %}
{% load static %}
{% block main_area %}

<script src="https://code.jquery.com/jquery-2.2.1.min.js"></script>
<script src="https://html2canvas.hertzen.com/dist/html2canvas.js"></script>
<link rel="stylesheet" href="{% static 'diary/css/post_list.css' %}">
<link rel="stylesheet" href="{% static 'diary/css/avatar.css' %}">

<div class="wrapper">
    <div class="wrapper__left">
        <div class="wrapper__left__body">
            <button type="button" id="save" style="left:96px;position:absolute;height:70px;border:none;cursor:pointer;margin-top:7px;"><img src="{%static 'diary/css/images/start.png' %}"></button>
            <div class="header">
              <div class="capture" id="capture">
                <div class=avatar>
                    <div id="dhair" style="height:100px;width:200px;margin-top:102px;margin-left:37px;" ondrop="drop(event)" ondragover="dragEnter(event)"></div>
                    <div id="dwear" style="height:210px;width:200px;margin-top:-101px;margin-left:36px;" ondrop="drop(event)" ondragover="dragEnter(event)"></div>
                     <div id="dacc" style="height:270px;width:200px;margin-top:-216px;margin-left:32px;" ondrop="drop(event)" ondragover="dragEnter(event)"></div>
                </div>
              </div>
            </div>
        </div>
        <script>
          $(function(){
            $("#save").click(function(){
              html2canvas($('#capture').get(0)).then(function(canvas){
               var data=canvas.toDataURL();
               //console.log(data);a
               //document.getElementById('img').appendChild(canvas)
                downloadURI(data, "new_profile.png");


                function downloadURI(uri, name){
                    var link = document.createElement("a");
                    link.download = name;
                    link.href = uri;
                    document.body.appendChild(link);
                    link.click();
                }

               //ajax 통신
               $.ajax({
                  async:false,
                  type:'POST',
                  url :"{% url 'diary:avatar_profile' %}",
                  data:{data:data},
                  success:function(result){
                    alert("프로필로 설정 완료!")
                  },
                  error: function(e){alert("프로필로 설정!")}
                });
              });
            });
          });
        </script>
    </div>

    <div class="wrapper__right">
        <div class="wrapper__right__body" style="position:relative">
            <img src="{% static 'diary/css/images/hearts4.png' %}" style="position:absolute; left:60px; top:55px; width:80px; height:30px">
            <div class="avatar-hair" style="position:absolute; left:150px; top:-30px">
                <img src="{% static 'diary/css/images/avatar/hair0.png' %}"style="width:265px; height:265px; cursor:pointer" id="avatar-hair" ondragstart="drag(event)" draggable="true">
            </div>
            <div class="hair-change" style="position:absolute; left:20px; top:90px; z-index:100">
                <img src="{% static 'diary/css/images/left.png' %}" style="width:50px; height:50px; cursor:pointer;" onclick="downhairButton()">
                <img src="{% static 'diary/css/images/hair.png' %}">
                <img src="{% static 'diary/css/images/right.png' %}" style="width:50px; height:50px; cursor:pointer;" onclick="uphairButton()">
            </div>
            <img src="{% static 'diary/css/images/hearts5.png' %}" style="position:absolute; left:60px; top:205px; width:80px; height:30px">
            <div class="avatar-clothes" style="position:absolute; left:150px; top:90px;">
                <img src="{% static 'diary/css/images/avatar/clothes0.png' %}" style="width:270px; height:270px; cursor:pointer" id="avatar-clothes" ondragstart="drag(event)" draggable="true">
            </div>
            <div class="clothes-change" style="position:absolute; left:20px; top:240px; z-index:100">
                <img src="{% static 'diary/css/images/left.png' %}" style="width:50px; height:50px; cursor:pointer;" onclick="downclothesButton()">
                <img src="{% static 'diary/css/images/wear.png' %}">
                <img src="{% static 'diary/css/images/right.png' %}" style="width:50px; height:50px; cursor:pointer;" onclick="upclothesButton()">
            </div>
            <img src="{% static 'diary/css/images/hearts6.png' %}" style="position:absolute; left:60px; top:345px; width:80px; height:30px">
            <div class="avatar-acc" style="position:absolute; left:150px; top: 250px">
                <img src="{% static 'diary/css/images/avatar/acc0.png' %}" style="width:275px; height:275px; cursor:pointer" id="avatar-acc" ondragstart="drag(event)" draggable="true">
            </div>
            <div class="acc-change" style="position:absolute; left:20px; top:380px; z-index:100">
                <img src="{% static 'diary/css/images/left.png' %}" style="width:50px; height:50px; cursor:pointer;" onclick="downaccButton()">
                <img src="{% static 'diary/css/images/acc.png' %}">
                <img src="{% static 'diary/css/images/right.png' %}" style="width:50px; height:50px; cursor:pointer;" onclick="upaccButton()">
            </div>

             <script>
                var hair_img = ["{% static 'diary/css/images/avatar/hair0.png' %}", "{% static 'diary/css/images/avatar/hair1.png' %}", "{% static 'diary/css/images/avatar/hair2.png' %}",
                "{% static 'diary/css/images/avatar/hair3.png' %}", "{% static 'diary/css/images/avatar/hair4.png' %}", "{% static 'diary/css/images/avatar/hair5.png' %}",
                "{% static 'diary/css/images/avatar/hair6.png' %}", "{% static 'diary/css/images/avatar/hair7.png' %}", "{% static 'diary/css/images/avatar/hair8.png' %}"]
                var clothes_img = ["{% static 'diary/css/images/avatar/clothes0.png' %}", "{% static 'diary/css/images/avatar/clothes1.png' %}", "{% static 'diary/css/images/avatar/clothes2.png' %}",
                "{% static 'diary/css/images/avatar/clothes3.png' %}", "{% static 'diary/css/images/avatar/clothes4.png' %}", "{% static 'diary/css/images/avatar/clothes5.png' %}",
                "{% static 'diary/css/images/avatar/clothes6.png' %}", "{% static 'diary/css/images/avatar/clothes7.png' %}", "{% static 'diary/css/images/avatar/clothes8.png' %}",
                "{% static 'diary/css/images/avatar/clothes9.png' %}"]
                var acc_img = ["{% static 'diary/css/images/avatar/acc0.png' %}", "{% static 'diary/css/images/avatar/acc1.png' %}", "{% static 'diary/css/images/avatar/acc2.png' %}",
                "{% static 'diary/css/images/avatar/acc3.png' %}","{% static 'diary/css/images/avatar/acc4.png' %}", "{% static 'diary/css/images/avatar/acc5.png' %}"]
                var hair_index = 0;
                var clothes_index = 0;
                var acc_index = 0;

                function uphairButton() {
                    if(hair_index>=8){hair_index=0;
                        }else{hair_index++;}
                    document.getElementById('avatar-hair').src = hair_img[hair_index];
                }
                function downhairButton() {
                    if(hair_index<=0){hair_index=8;
                        }else{hair_index--;}
                    document.getElementById('avatar-hair').src = hair_img[hair_index];
                }

                function upclothesButton() {
                if(clothes_index>=11){clothes_index=0;
                    }else{clothes_index++;}
                    document.getElementById('avatar-clothes').src = clothes_img[clothes_index];
                }
                function downclothesButton() {
                if(clothes_index<=0){clothes_index=9;
                    }else{clothes_index--;}
                    document.getElementById('avatar-clothes').src = clothes_img[clothes_index];
                }

                function upaccButton() {
                if(acc_index>=3){acc_index=0;
                    }else{acc_index++;}
                    document.getElementById('avatar-acc').src = acc_img[acc_index];
                }
                function downaccButton() {
                if(acc_index<=0){acc_index=5;
                    }else{acc_index--;}
                    document.getElementById('avatar-acc').src = acc_img[acc_index];
                }

                function dragEnter(ev) {
                    ev.preventDefault();
                }

                function drag(ev) {
                    ev.dataTransfer.setData("text", ev.target.id);
                }

                function drop(ev) {
                    ev.preventDefault();
                    var data = ev.dataTransfer.getData("text");
                    if(data==='avatar-hair'){
                        document.getElementById('dhair').appendChild(document.getElementById(data));

                    } else if(data==='avatar-clothes'){
                        document.getElementById('dwear').appendChild(document.getElementById(data));

                    }else if(data==='avatar-acc'){
                        document.getElementById('dacc').appendChild(document.getElementById(data));
                    }
                }

              </script>
        </div>
    </div>
</div>


{% endblock %}
</html>

diary/templates/diary/guest_book.html
<!DOCTYPE html>
<html lang="ko">

{% extends 'single_pages/base.html' %}
{% load static %}
{% load mathfilters %}
{% block main_area %}

<link rel="stylesheet" href="{% static 'diary/css/post_list.css' %}">
<link rel="stylesheet" href="{% static 'diary/css/guest_book.css' %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poor+Story&display=swap" rel="stylesheet">

<div class="wrapper">
    <div class="wrapper__left">
        <div class="wrapper__left__body">
            <div class="header">
                <img src="{% static 'diary/css/images/tape.png' %}" style="z-index:200; position:absolute; top:94px; left:54px; width:90px;">
            <div class=our_book id="guest-{{ guest.pk }}">
                {% for guest in page_obj %}
                <img src='{{guest.sticker}}' draggable="true" onmouseenter="move(this.id)" style="width:77px; cursor:pointer;" id="sticker-{{ guest.pk }}" data-bs-target="#deleteStickerModal-{{ guest.pk }}">

            <!-- Modal -->
               <div class="modal hidden" id="deleteStickerModal-{{ guest.pk }}" tabindex="-1" aria-labelledby="deleteStickerModalLabel" aria-hidden="true">
                  <div class="bg" id="bg-{{ guest.pk }}"></div>
                  <div class="modalBox">
                     <div class="head" style="text-align:center;"><p style="font-family: 'Poor Story', cursive;font-size:17px;text-align: center;"><strong>FROM.</strong> {{guest.author}}</p></div>
                     <p style="font-family: 'Poor Story', cursive;font-size:17px;margin-top:5px;text-align: center;padding-top:5px;word-wrap:break-word;">
                        <u>{{guest.content}}</u>
                     </p>
                  </div>
               </div>
               <script>
                  var close = () =>{
                     document.getElementById("deleteStickerModal-{{ guest.pk }}").classList.add("hidden");
                  }
                  document.querySelector("#sticker-{{ guest.pk }}").addEventListener("contextmenu",function(e){
                     e.preventDefault();
                     document.getElementById("deleteStickerModal-{{ guest.pk }}").classList.remove("hidden");
                  },false);
                  document.querySelector("#bg-{{ guest.pk }}").addEventListener("click",close);
               </script>
                {% endfor %}

               <script>
                  function move(ev) {

                    let sticker = document.getElementById(ev);
                    sticker.onmousedown = function(event) {
                        let shiftX = event.clientX - sticker.getBoundingClientRect().left;
                        let shiftY = event.clientY - sticker.getBoundingClientRect().top;

                        sticker.style.position = 'absolute';
                        sticker.style.zIndex = 100;
                        document.body.append(sticker);

                        moveAt(event.pageX, event.pagY);

                        // 초기 좌표에서부터 스티커 이동
                        function moveAt(pageX, pageY) {
                            sticker.style.left = pageX - shiftX + 'px';
                            sticker.style.top = pageY - shiftY + 'px';
                        }

                        function onMouseMove(event) {
                            moveAt(event.pageX, event.pageY);
                        }

                        // mousemove로 스티커 움직이기
                        document.addEventListener('mousemove', onMouseMove);

                        // 스티커를 드롭하고, 불필요한 핸들러 제거
                        sticker.onmouseup = function() {
                            document.removeEventListener('mousemove', onMouseMove);
                            sticker.onmouseup = null;
                        };
                    };

                    sticker.ondragstart = function() {
                        return false;
                    };
                  };

                </script>

                </div>
                                <!-- Pagination -->
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}">
                            <p style="position:absolute; font-family:'Poor Story', cursive; font-size:15px; color:black; left:210px; top:540px; z-index:200"/>Prev</p>
                        </a>
                    {% else %}
                        <p style="position:absolute; font-family:'Poor Story', cursive; font-size:15px; color:black; left:210px; top:540px; z-index:200"/>Prev</p>
                    {% endif %}
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">
                            <p style="position:absolute; font-family:'Poor Story', cursive; font-size:15px; color:black; left:300px; top:540px; z-index:200"/>Next</p>
                        </a>
                    {% else %}
                        <p style="position:absolute; font-family:'Poor Story', cursive; font-size:15px; color:black; left:300px; top:540px; z-index:200"/>Next</p>
                    {% endif %}
            </div>
            <img src="{% static 'diary/css/images/tape.png' %}" style="position:absolute; top:483px; left:394px; width:90px;">

        </div>
    </div>
    <div class="wrapper__right">
        <div class="wrapper__right__body" style="font-family:'Poor Story', cursive;">
                <form action="{% url 'diary:guest_write' %}" method="post">
                   {% csrf_token %}
                      <tr>
                         <td>
                            Nickname : <input type="text" id="test" name="author" size=20 style="font-size:11px; font-weight:bold;">
                         </td>
                      </tr>
                      <tr>
                          <br>
                         Content :<textarea name="content" id="content" style="font-size:11px; height:65px; width:330px; resize:none; margin-top:3px;" required></textarea>
                      </tr>
                      <tr>
                        Sticker :
                        <div class="table" style="padding-top:5px;">
                           <input type = "radio" name = "sticker" value = "{% static 'diary/css/images/sticker/boat.png' %}" style="margin-left:15px;"><img src="{% static 'diary/css/images/sticker/boat.png' %}" style="height:80px;width:80px;">
                           <input type = "radio" name = "sticker" value = "{% static 'diary/css/images/sticker/airplane.png' %}" style="margin-left:15px;"><img src="{% static 'diary/css/images/sticker/airplane.png' %}" style="height:80px;width:80px;">
                           <input type = "radio" name = "sticker" value = "{% static 'diary/css/images/sticker/bird.png' %}" style="margin-left:15px;"><img src="{% static 'diary/css/images/sticker/bird.png' %}" style="height:80px;width:80px;">
                        </div>
                        <div class="table" style="padding-top:15px;">
                           <input type = "radio" name = "sticker" value = "{% static 'diary/css/images/sticker/board.png' %}" style="margin-left:15px;"><img src="{% static 'diary/css/images/sticker/board.png' %}" style="height:80px;width:80px;">
                           <input type = "radio" name = "sticker" value = "{% static 'diary/css/images/sticker/fish.png' %}" style="margin-left:15px;"><img src="{% static 'diary/css/images/sticker/fish.png' %}" style="height:80px;width:80px;">
                           <input type = "radio" name = "sticker" value = "{% static 'diary/css/images/sticker/starfish.png' %}" style="margin-left:15px;"><img src="{% static 'diary/css/images/sticker/starfish.png' %}" style="height:80px;width:80px;">
                        </div>
                        <div class="table" style="padding-top:15px;">
                           <input type = "radio" name = "sticker" value = "{% static 'diary/css/images/sticker/turtle.png' %}" style="margin-left:15px;"><img src="{% static 'diary/css/images/sticker/turtle.png' %}" style="height:80px;width:80px;">
                           <input type = "radio" name = "sticker" value = "{% static 'diary/css/images/sticker/shell.png' %}" style="margin-left:15px;"><img src="{% static 'diary/css/images/sticker/shell.png' %}" style="height:80px;width:80px;">
                           <input type = "radio" name = "sticker" value = "{% static 'diary/css/images/sticker/palm.png' %}" style="margin-left:15px;"><img src="{% static 'diary/css/images/sticker/palm.png' %}" style="height:80px;width:80px;">
                        </div>
                     </tr>
                      <tr>
                          <button type="submit" style="font-size:9px; bottom:30px; float:right;">Enter</button>
                      </tr>
                   <br>
                   </br>
                </form>

        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
{% endblock %}

single_pages/templates/single_pages/list.html
<!DOCTYPE html>
{% load mathfilters %}
{% load static %}

<html lang="ko">
<link rel="stylesheet" href="{% static 'single_pages/css/comment.css' %}">
<body style="background-color:#F5F5F5">
<div id="comment-{{ comment.pk }}">
   <form action="{% url 'single_pages:write' %}" method="post">
      {% csrf_token %}
         <tr>
            <td colspan="5">
               <input type="text" id="test" name="question" size=25 style="font-size:10px; padding-top:7px; text-align:justify; font-weight:bold;" value="Click Heart!">
               <img src="{% static 'diary/css/images/favicon.ico' %}" onclick="getValueInput()">
                  <script>
                     function que(){
                     var A=new Array();
                     A[0]= `살면서 놓쳤던 인연 중에 한 명을 다시
                      잡을 수 있다면 누굴 잡을 것인지?`
                     A[1]="내가 좋아하는 계절+시간대는?"
                     A[2]="나는 몰랐지만 남이 말해줘서 알게된 나의 특징은 무엇이 있는지?"
                     A[3]="내가 빠지지 않고 하는 하루의 일과 중 가장 특이한 행동은?"
                     A[4]="인상 깊었던 생일은?"
                     A[5]="아직도 기억하고 있는 꿈은?"
                     A[6]="가족을 제외하고 내 인생에 가장 영향력 있던 사람은?"
                     A[7]="특이하고 사소한 장점을 자랑해본다면?"
                     A[8]="내가 자주하는 상상은?"
                     A[9]="내가 가장 좋아하는 노래와 이유는?"
                     A[10]="요즘 가장 고민되거나 힘든 일은?"
                     A[11]="가장 행복했던 기억은?"
                     var rend=Math.floor(A.length *Math.random());
                     return A[rend];
                  }
                  const getValueInput = () =>{
                     let inputValue=que();
                     document.getElementById("test").value = inputValue;
                  }
                  </script>
            </td>
         </tr>
         <tr>
            <td colspan=5><textarea name="content" id="content" placeholder="Check out our answers!" style="font-size:9px; height:65px; width:300px; resize:none; margin-top:3px;"></textarea></td>
         </tr>
         <tr>
            {% if user.is_superuser %}
            <td colspan=4 align=right>
               <button type="submit" style="font-size:9px; left:270px; top:98px; position:absolute">Enter</button>
            </td>
            {% endif %}
         </tr>
      <br>
      </br>
   </form>

         {% for comment in commentlist %}
            <table style="font-size:9px;">
               <tr>
                  <td>Q :  {{comment.question}}</td>
               </tr>
               <tr>
                  <td colspan=4>
                  A: {{ comment.content }}

                  </td>
               </tr>
               {% if user.is_superuser %}
               <td><button type="button" style="font-size:9px;" id="comment-{{ comment.pk }}" data-toggle="modal"
                  data-target="#deleteCommentModal-{{ comment.pk }}">Delete</button></td>
               <!-- Modal -->
               <div class="modal hidden" id="deleteCommentModal-{{ comment.pk }}" aria-labelledby="deleteCommentModalLabel" tabindex="-1" aria-hidden="true">
                  <div class="bg" id="bg-{{ comment.pk }}"></div>
                  <div class="modalBox">
                     <div class="head"></div>
                     <p class="modal-title" id="deleteModalLabel" style="font-size:15px;">삭제하시겠습니까?</p>
                     <a role="button" href="{% url 'single_pages:delete' comment.id %}"><button>Yes</button></a>
                     <button type="button" id="delcomment-{{ comment.pk }}">No</button>
                  </div>
               </div>
               {% endif %}
               <script>
                  var open = () =>{
                     document.getElementById("deleteCommentModal-{{ comment.pk }}").classList.remove("hidden");
                  }
                  var close = () =>{
                     document.getElementById("deleteCommentModal-{{ comment.pk }}").classList.add("hidden");
                  }
                  document.querySelector("#comment-{{ comment.pk }}").addEventListener("click",open);
                  document.querySelector("#delcomment-{{ comment.pk }}").addEventListener("click", close);
                  document.querySelector("#bg-{{ comment.pk }}").addEventListener("click", close);
               </script>
            </table>
            <br>
         {% endfor %}
</div>
</body>
</html>